# Generated by Django 3.1.4 on 2020-12-16 01:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_stories',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='circle.FinishedStory'),
        ),
        migrations.CreateModel(
            name='WorkingStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_name', models.TextField()),
                ('text', models.TextField()),
                ('authors_list_json', models.TextField()),
                ('authors', models.ManyToManyField(blank=True, related_name='wip', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
