# Generated by Django 3.1.4 on 2020-12-17 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0002_auto_20201216_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingstory',
            old_name='authors_list_json',
            new_name='turn_order_json',
        ),
    ]
