# Generated by Django 3.1.4 on 2021-01-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0003_auto_20210121_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
