# Generated by Django 3.1.4 on 2021-01-25 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0007_auto_20210125_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='max_user_ct',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='circle',
            name='threshold_user_ct',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
