# Generated by Django 3.1.4 on 2021-01-25 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0008_auto_20210125_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_since',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='circle',
            name='max_user_ct',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='circle',
            name='threshold_user_ct',
            field=models.IntegerField(),
        ),
    ]
