# Generated by Django 3.1.4 on 2021-01-25 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0009_auto_20210125_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
