# Generated by Django 3.1.4 on 2021-01-28 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0010_auto_20210125_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='proposed_ending',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ending_proposed', to=settings.AUTH_USER_MODEL),
        ),
    ]
