# Generated by Django 3.1.4 on 2021-02-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0011_circle_proposed_ending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='approved_ending',
            new_name='approved_proposal',
        ),
        migrations.RenameField(
            model_name='circle',
            old_name='proposed_ending',
            new_name='proposing_user',
        ),
        migrations.AddField(
            model_name='circle',
            name='active_proposal',
            field=models.CharField(blank=True, choices=[('ES', 'End Story'), ('NP', 'New Paragraph')], max_length=2, null=True),
        ),
    ]
