# Generated by Django 3.1.4 on 2021-02-19 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0012_auto_20210212_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked_stories',
        ),
    ]
